apiVersion: v1
kind: Service
metadata:
  labels:
    run: smtp-server
  name: smtp-server
  namespace: monitoring
spec:
  ports:
  - name: smtp
    port: 25
    targetPort: smtp
  selector:
    run: smtp-server
